name: cypress-cloud.yml

on: 
  workflow_dispatch:
    inputs: 
      spec:
        description: Run by cypress command line
        default:  cypress/e2e/*

jobs: 
  cypress-e2e-electron:
    runs-on: ubutu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3.3.0
        
      - name: Cypress run  
        uses: cypress-io/github-action@v5.3.0
        with:
          install-command: yarn install
          browser: electron
          record: true
          group: UI electron
          spec: $ {{ github.event.inputs.spec }}
        env:
          CYPRESS_RECORD_KEY: 2123d95b-cad7-46c1-b9b1-cc75f6a91422
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
            
          
          
        
        
  
